
-- Performance Indexes for Attendance and Locations
-- Generated by TraeAI

CREATE INDEX IF NOT EXISTS idx_attendance_records_company_clockin ON attendance_records (company_id, clock_in_time DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_records_user_clockin ON attendance_records (user_id, clock_in_time DESC);

-- Composite index for AutoAttendanceService location queries
CREATE INDEX IF NOT EXISTS idx_user_locations_company_created_user ON user_locations (company_id, created_at DESC, user_id);

-- Index for User filtering in AutoAttendanceService
CREATE INDEX IF NOT EXISTS idx_users_company_active ON users (company_id, is_active) WHERE deleted_at IS NULL;
